import { colors } from "./color";
import { PlaylistInterface, SongInterface } from "./typesInterface";
import { v4 as uuidv4 } from "uuid";

export const songs: SongInterface[] = [
  {
    id: uuidv4().slice(0, 4),
    title: "I'm a dev 4 you",
    image: `/images/Casette.png`,
    artists: "DJ Toggle",
    album: "Release Beats",
    albumColor: ["#FFB6C1", "#F7727E", "#92C5F2", "#E8AD5C"],
    duration: "2:56",
  },
  {
    id: uuidv4().slice(0, 4),
    title: "Code Me Maybe",
    image: `/images/Code me maybe.png`,
    artists: "Blast Radius",
    album: "Targeted Experience",
    albumColor: ["#FFB6C1", "#F7727E", "#92C5F2", "#E8AD5C"],
    duration: "3:53",
  },
  {
    id: uuidv4().slice(0, 4),
    title: "Crash and Burn",
    image: `/images/Spotlight.png`,
    artists: "The DevOperatos",
    album: "Instant Recovery",
    albumColor: ["#FFB6C1", "#F7727E", "#92C5F2", "#E8AD5C"],
    duration: "2:23",
  },
  {
    id: uuidv4().slice(0, 4),
    title: "MMMbyte",
    image: `/images/Kill switcher cover.png`,
    artists: "Terminal Launch",
    album: "RELEASE",
    albumColor: ["#FFB6C1", "#F7727E", "#92C5F2", "#E8AD5C"],
    duration: "5:13",
  },
  {
    id: uuidv4().slice(0, 4),
    title: "Talk Contexts to Me",
    image: `/images/Used to code me cover.png`,
    artists: "Lost Weekends",
    album: "Reclaim",
    albumColor: ["#FFB6C1", "#F7727E", "#92C5F2", "#E8AD5C"],
    duration: "3:22",
  },
];

export const moreNewSongs: SongInterface[] = [
  {
    id: uuidv4().slice(0, 4),
    title: "I'm a dev 4 you",
    image: `/images/Casette.png`,
    artists: "DJ Toggle",
    album: "Release Beats",
    albumColor: ["#FFB6C1", "#F7727E", "#92C5F2", "#E8AD5C"],
    duration: "2:56",
  },
  {
    id: uuidv4().slice(0, 4),
    title: "Code Me Maybe",
    image: `/images/Code me maybe.png`,
    artists: "Blast Radius",
    album: "Targeted Experience",
    albumColor: ["#FFB6C1", "#F7727E", "#92C5F2", "#E8AD5C"],
    duration: "3:53",
  },
  {
    id: uuidv4().slice(0, 4),
    title: "Crash and Burn",
    image: `/images/Spotlight.png`,
    artists: "The DevOperatos",
    album: "Instant Recovery",
    albumColor: ["#FFB6C1", "#F7727E", "#92C5F2", "#E8AD5C"],
    duration: "2:23",
  },
  {
    id: uuidv4().slice(0, 4),
    title: "MMMbyte",
    image: `/images/Kill switcher cover.png`,
    artists: "Terminal Launch",
    album: "RELEASE",
    albumColor: ["#FFB6C1", "#F7727E", "#92C5F2", "#E8AD5C"],
    duration: "5:13",
  },
  {
    id: uuidv4().slice(0, 4),
    title: "Talk Contexts to Me",
    image: `/images/Used to code me cover.png`,
    artists: "Lost Weekends",
    album: "Reclaim",
    albumColor: ["#FFB6C1", "#F7727E", "#92C5F2", "#E8AD5C"],
    duration: "3:22",
  },
];

export const playlists: PlaylistInterface[] = [
  {
    id: "liked-songs",
    title: "Liked Songs",
    color: colors.emerald,
    cover: "/images/heart.png",
    songs: [...songs, ...moreNewSongs],
    createdBy: "User",
  },
  {
    id: "shipper-beats",
    title: "Shipper Beats",
    color: colors.pink,
    cover: "/images/Shipper beats cover.png",
    songs: [...songs, ...moreNewSongs],
    createdBy: "User",
  },
  {
    id: "rollback-mix",
    title: "Rollback Mix",
    color: colors.indigo,
    cover: "/images/Rollback Mix cover.png",
    songs: [...songs, ...moreNewSongs],
    createdBy: "User",
  },
];

export const moreNewPlaylists: PlaylistInterface[] = [
  {
    id: "launch-party-jams",
    title: "Launch Party Jams",
    color: colors.green,
    cover: "/images/Launch Party Jams cover.png",
    songs: [...songs, ...moreNewSongs],
    createdBy: "User",
  },
  {
    id: "cosmic-vibes",
    title: "Cosmic Vibes",
    color: colors.rose,
    cover: "/images/Cosmic vibes cover.png",
    songs: [...songs, ...moreNewSongs],
    createdBy: "User",
  },
  {
    id: "codebreaker-blues",
    title: "Codebreaker Blues",
    color: colors.blue,
    cover: "/images/Codebreaker blues cover.png",
    songs: [...songs, ...moreNewSongs],
    createdBy: "User",
  },
];

export const defaultListOfCohereGeneratedSongs = [
  [
    {
      id: "1",
      title: "Don't Go Yet",
      artists: "Camilla Cabello",
      album: "Familia",
      albumColor: ["#FCE6DD", "#9D90F0", "#FCB9E3", "#E1B6D3"],
      duration: "3:26",
      playlistName: "Songs to Dance and Prance To",
    },
    {
      id: "2",
      title: "All Of The Girls You Loved Before",
      artists: "Taylor Swift",
      album: "Midnights",
      albumColor: ["#2C004B", "#8B8B8B", "#5A5A5A", "#7B5E88"],
      duration: "3:27",
      playlistName: "Let's Stay Up All Night",
    },
    {
      id: "3",
      title: "Leave the Door Open",
      artists: "Bruno Mars, Anderson .Paak & Silk Sonic",
      album: "An Evening With Silk Sonic",
      albumColor: ["#2D2060", "#353535", "#E1B6D3", "#A4245E"],
      duration: "3:16",
      playlistName: "Steal the Night",
    },
    {
      id: "4",
      title: "Special",
      artists: " Lizzo",
      album: "Special",
      albumColor: ["#7B47F5", "#3B2B4D", "#7B5B97", "#1B1B1B"],
      duration: "2:51",
      playlistName: "Let's Get Special",
    },
    {
      id: "5",
      title: 'All We Know (from the Netflix Film "The Harder They Fall")',
      artists: "The Weeknd",
      album: "The Harder They Fall (Original Motion Picture Soundtrack)",
      albumColor: ["#2C1A41", "#4B3D56", "#4B4F5A", "#4A3B3A"],
      duration: "4:21",
      playlistName: "When the Sun Goes Down",
    },
    {
      id: "6",
      title: "Lalala",
      artists: "Y2K and bbno$",
      album: "Lalala",
      albumColor: ["#3B2A48", "#3B6753", "#7B5B77", "#3B3949"],
      duration: "2:38",
      playlistName: "The Party's Just Beginning",
    },
    {
      id: "7",
      title: "Lost Cause",
      artists: "Billie Eilish",
      album: "Happier Than Ever",
      albumColor: ["#323232", "#C4C4C4", "#4B4B4B", "#7B7B7B"],
      duration: "2:42",
      playlistName: "The Late Night Revelry",
    },
    {
      id: "8",
      title: "Mr. Perfectly Fine",
      artists: "Pink Floyd",
      album: "The Later Years (1987-2019)",
      albumColor: ["#9B1C1C", "#3B3B3B", "#E2B2AB", "#5C5C5C"],
      duration: "3:20",
      playlistName: "Party Like It's 1999",
    },
    {
      id: "9",
      title: "Party For One",
      artists: "Carly Rae Jepsen",
      album: "Dedicated",
      albumColor: ["#3B2A49", "#C4C4C4", "#AF004A", "#7B7B7B"],
      duration: "3:25",
      playlistName: "Let's Party",
    },
    {
      id: "10",
      title: "The Business",
      artists: "Tiësto",
      album: "The Business",
      albumColor: ["#342541", "#EBEBEB", "#452741", "#E2A7AF"],
      duration: "2:27",
      playlistName: "The Party Tycoon",
    },
  ],
  [
    {
      id: "1",
      title: "Dynamite",
      artists: "BTS",
      album: "BE",
      albumColor: ["#0C3051", "#9B59B6", "#7B3294", "#F7BDE5"],
      duration: "3:19",
      playlistName: "Friday Night Feels",
    },
    {
      id: "2",
      title: "Leave the Door Open",
      artists: "Bruno Mars, Anderson .Paak",
      album: "An Evening With Silk Sonic",
      albumColor: ["#1B5D8A", "#3C3A44", "#7B3294", "#EBA9D0"],
      duration: "3:27",
      playlistName: "The Hangout",
    },
    {
      id: "3",
      title: "Peaches",
      artists: "Justin Bieber feat. Daniel Caesar & Giveon",
      album: "Justice",
      albumColor: ["#9B59B6", "#3C3A44", "#8B8A54", "#F5AFCE"],
      duration: "3:09",
      playlistName: "Sunny Days",
    },
    {
      id: "4",
      title: "Good 4 U",
      artists: "Olivia Rodrigo",
      album: "SOUR",
      albumColor: ["#7B3294", "#F5AFCE", "#E1A585", "#BF8F68"],
      duration: "2:58",
      playlistName: "Breakup Bops",
    },
    {
      id: "5",
      title: "Kiss Me More",
      artists: "Doja Cat feat. SZA",
      album: "Planet Her",
      albumColor: ["#C05B64", "#1B5D8A", "#7B3294", "#FFD97D"],
      duration: "3:26",
      playlistName: "Girls Night In",
    },
    {
      id: "6",
      title: "Mr. Morale & the Big Steppers",
      artists: "Kendrick Lamar",
      album: "Mr. Morale & the Big Steppers",
      albumColor: ["#0C3051", "#9B8BB1", "#F29EA6", "#FFD97D"],
      duration: "7:40",
      playlistName: "Step Into My World",
    },
    {
      id: "7",
      title: "As It Was",
      artists: "Harry Styles",
      album: "Harry's House",
      albumColor: ["#7B3294", "#BF8F68", "#E1A585", "#F2C94C"],
      duration: "3:02",
      playlistName: "House Party",
    },
    {
      id: "8",
      title: "Stop This Train",
      artists: "Shawn Mendes",
      album: "Wonder",
      albumColor: ["#3C3A44", "#7B8AB2", "#F29EA6", "#FFD97D"],
      duration: "3:03",
      playlistName: "Road Trip",
    },
    {
      id: "9",
      title: "Daylight",
      artists: "Joji",
      album: "Smooch",
      albumColor: ["#7B8AB2", "#EBA9D0", "#A17975", "#FFD97D"],
      duration: "2:53",
      playlistName: "Romantic Chill",
    },
    {
      id: "10",
      title: "All of the Girls You Loved Before",
      artists: "Taylor Swift",
      album: "Fearless (Taylor's Version)",
      albumColor: ["#E1A585", "#0C3051", "#F7BDE5", "#FFD97D"],
      duration: "3:15",
      playlistName: "Throwing Back Classics",
    },
  ],
  [
    {
      id: "1",
      title: "Dynamite",
      artists: "BTS",
      album: "BE",
      albumColor: ["#EDCFDF", "#F4EBD5", "#B69F95", "#9BA5A8"],
      duration: "3:19",
      playlistName: "BTS Bangers",
    },
    {
      id: "2",
      title: "Leave the Door Open",
      artists: " Silk Sonic",
      album: "An Evening With Silk Sonic",
      albumColor: ["#C9FFC5", "#F4AF75", "#A3BE8D", "#E1B65F"],
      duration: "3:14",
      playlistName: "Retro Funk",
    },
    {
      id: "3",
      title: "Peaches",
      artists: "Justin Bieber feat. Daniel Caesar & Giveon",
      album: "Justice",
      albumColor: ["#FFCEB9", "#F57C00", "#7B3294", "#B75200"],
      duration: "3:18",
      playlistName: "R&B Party",
    },
    {
      id: "4",
      title: "Good 4 U",
      artists: "Olivia Rodrigo",
      album: "SOUR",
      albumColor: ["#FF8F00", "#EA5029", "#7B3294", "#EA433E"],
      duration: "3:21",
      playlistName: "Pop Powerhouse",
    },
    {
      id: "5",
      title: "Kiss Me More",
      artists: "Doja Cat feat. SZA",
      album: "Planet Her",
      albumColor: ["#FFC0CB", "#7B3294", "#F57C00", "#5B4500"],
      duration: "3:13",
      playlistName: "Hiptronica",
    },
    {
      id: "6",
      title: "Rapstar",
      artists: "Lizzo",
      album: "Special",
      albumColor: ["#FFEFD1", "#B35F73", "#F4AF75", "#9C6055"],
      duration: "2:53",
      playlistName: "Female Empowerment Anthems",
    },
    {
      id: "7",
      title: "Super Gremlin",
      artists: "Kanye West feat. Playboi Carti",
      album: "Donda",
      albumColor: ["#FFC1AB", "#A1345D", "#D83B36", "#7B3294"],
      duration: "3:08",
      playlistName: "Party Anthems",
    },
    {
      id: "8",
      title: "Montero (Call Me By Your Name)",
      artists: "Lil Nas X",
      album: "Montero",
      albumColor: ["#F4AF75", "#C05B5D", "#F57C00", "#9C6055"],
      duration: "2:17",
      playlistName: "TikTok Hits",
    },
    {
      id: "9",
      title: "Hard Place",
      artists: "Halsey",
      album: "Manic",
      albumColor: ["#FFDAB9", "#EA5029", "#8F1F56", "#EA433E"],
      duration: "3:25",
      playlistName: "Indie Dance Party",
    },
    {
      id: "10",
      title: "All Too Well (10 minute Version)",
      artists: "Taylor Swift",
      album: "Red (Taylor's Version)",
      albumColor: ["#FF8F00", "#FF5B8C", "#9C6055", "#EA433E"],
      duration: "10:13",
      playlistName: "Memory Lane",
    },
  ],
  [
    {
      id: "1",
      title: "Bad Habits (From The 'Demon Slayer: Kimetsu No Yaiba' Opening)",
      artists: "Ed Sheeran",
      album: "= (Equals)",
      albumColor: ["#001C57", "#3D2400", "#7B3200", "#DC2C00"],
      duration: "3:32",
      playlistName: "Pop Hits That Pack a Bite",
    },
    {
      id: "2",
      title: "Leave The Door Open",
      artists: "Bruno Mars, Anderson .Paak & Silk Sonic",
      album: "An Evening With Silk Sonic",
      albumColor: ["#1B5F1B", "#3F2B1B", "#7B3A2C", "#D83B1E"],
      duration: "3:27",
      playlistName: "The Silk Sonic Show",
    },
    {
      id: "3",
      title: "Players",
      artists: "Coi Leray",
      album: "Eternal Atake (Deluxe)",
      albumColor: ["#4B3F2E", "#8B5B71", "#C05B5B", "#F47C5F"],
      duration: "2:51",
      playlistName: "The A-Lister",
    },
    {
      id: "4",
      title: "Mood",
      artists: "24kGoldn",
      album: "El Dorado",
      albumColor: ["#4B5A71", "#8A3D3D", "#B35F5F", "#F47C5F"],
      duration: "4:28",
      playlistName: "Chill Golden Vibes",
    },
    {
      id: "5",
      title: "Sunflower",
      artists: "Post Malone & Swae Lee",
      album: "Spider-Man: Into the Spider-Verse (Soundtrack)",
      albumColor: ["#1F3397", "#4D2D80", "#B45F0E", "#F09513"],
      duration: "2:43",
      playlistName: "Post Malone's Web",
    },
    {
      id: "6",
      title: "Good 4 U",
      artists: "Olivia Rodrigo",
      album: "SOUR",
      albumColor: ["#473B98", "#7B2567", "#AF1F4C", "#ED4C2F"],
      duration: "3:21",
      playlistName: "SOUR Bursts of Emotion",
    },
    {
      id: "7",
      title: "Creepin' (feat. Metro Boomin)",
      artists: "The Weeknd",
      album: "After Hours",
      albumColor: ["#2A1A71", "#3D2875", "#6B4B87", "#AF75E4"],
      duration: "3:58",
      playlistName: "The Weekend's After Hours",
    },
    {
      id: "8",
      title: "Daylight",
      artists: "Harry Styles",
      album: "Fine Line",
      albumColor: ["#2D1A5A", "#332638", "#6B5662", "#9E8173"],
      duration: "3:40",
      playlistName: "Day and Night",
    },
    {
      id: "9",
      title: "Happier Than Ever",
      artists: "Billie Eilish",
      album: "Happier Than Ever",
      albumColor: ["#2C1B5A", "#332638", "#6B5662", "#9E7B6F"],
      duration: "3:30",
      playlistName: "The Billie Breeze",
    },
    {
      id: "10",
      title: "Good Life (feat. Orange County Mix)",
      artists: "Kanye West",
      album: "Donda",
      albumColor: ["#3D1B5F", "#6B3A45", "#9E6B3F", "#D67C7A"],
      duration: "3:00",
      playlistName: "Kanye's Gospel",
    },
  ],
];

export const defaultListOfClaudeGeneratedSongs = [
  [
    {
      id: "1",
      title: "About Damn Time",
      artists: "Lizzo",
      album: "Special",
      albumColor: ["#FFC300", "#FF6F61", "#00A2AE", "#008893"],
      duration: "03:01",
      playlistName: "Good Vibes Summer Bops",
    },
    {
      id: "2",
      title: "As It Was",
      artists: "Harry Styles",
      album: "Harry's House",
      albumColor: ["#B29F94", "#7E6C62", "#4E4842", "#302826"],
      duration: "02:57",
      playlistName: "Chill Summer Jams",
    },
    {
      id: "3",
      title: "Break My Soul",
      artists: "Beyoncé",
      album: "Renaissance",
      albumColor: ["#000000", "#FF2600", "#FF8000", "#FFFF00"],
      duration: "04:06",
      playlistName: "Get Your Dance On",
    },
    {
      id: "4",
      title: "Cold Heart (PNAU Remix)",
      artists: "Elton John, Dua Lipa",
      album: "Rocket Hour",
      albumColor: ["#FF0000", "#FF6600", "#FFFF00", "#006600"],
      duration: "04:01",
      playlistName: "Party All Night Long",
    },
    {
      id: "5",
      title: "First Class",
      artists: "Jack Harlow",
      album: "Come Home The Kids Miss You",
      albumColor: ["#FFCC00", "#FF9900", "#FF6600", "#CC3300"],
      duration: "03:12",
      playlistName: "Turn Up The Beats",
    },
    {
      id: "6",
      title: "Girls Want Girls (with Lil Baby)",
      artists: "Drake",
      album: "Honestly, Nevermind",
      albumColor: ["#0099FF", "#33CCFF", "#66FFFF", "#99FFFF"],
      duration: "03:23",
      playlistName: "Summer Love Jamz",
    },
    {
      id: "7",
      title: "About Damn Time",
      artists: "Lizzo",
      album: "Special",
      albumColor: ["#FFC300", "#FF6F61", "#00A2AE", "#008893"],
      duration: "03:01",
      playlistName: "Good Vibes Summer Bops",
    },
    {
      id: "8",
      title: "As It Was",
      artists: "Harry Styles",
      album: "Harry's House",
      albumColor: ["#B29F94", "#7E6C62", "#4E4842", "#302826"],
      duration: "02:57",
      playlistName: "Chill Summer Jams",
    },
    {
      id: "9",
      title: "Break My Soul",
      artists: "Beyoncé",
      album: "Renaissance",
      albumColor: ["#000000", "#FF2600", "#FF8000", "#FFFF00"],
      duration: "04:06",
      playlistName: "Get Your Dance On",
    },
    {
      id: "10",
      title: "Cold Heart (PNAU Remix)",
      artists: "Elton John, Dua Lipa",
      album: "Rocket Hour",
      albumColor: ["#FF0000", "#FF6600", "#FFFF00", "#006600"],
      duration: "04:01",
      playlistName: "Party All Night Long",
    },
  ],
  [
    {
      id: "1",
      title: "Dance Monkey",
      artists: "Tones And I",
      album: "The Kids Are Coming",
      albumColor: ["#E8A87C", "#6D4C41", "#B88E70", "#F5E8D3"],
      duration: "03:48",
      playlistName: "Party pop dance floor bangers",
    },
    {
      id: "2",
      title: "Don't Start Now",
      artists: "Dua Lipa",
      album: "Future Nostalgia",
      albumColor: ["#FF6978", "#FFE0B2", "#BDD2FF", "#FFC8DD"],
      duration: "03:05",
      playlistName: "Dance your socks off hits",
    },
    {
      id: "3",
      title: "Blinding Lights",
      artists: "The Weeknd",
      album: "After Hours",
      albumColor: ["#660099", "#FFD700", "#FF9900", "#FF0000"],
      duration: "03:48",
      playlistName: "Late night cruise anthems",
    },
    {
      id: "4",
      title: "Peaches",
      artists: "Justin Bieber feat. Daniel Caesar, Giveon",
      album: "Justice",
      albumColor: ["#FFD43B", "#FFE4B5", "#F5DEB3", "#D9BA8C"],
      duration: "03:51",
      playlistName: "Summer road trip bops",
    },
    {
      id: "5",
      title: "Good 4 U",
      artists: "Olivia Rodrigo",
      album: "SOUR",
      albumColor: ["#FF6978", "#FFE0B2", "#BDD2FF", "#FFC8DD"],
      duration: "02:51",
      playlistName: "Angsty breakup anthems",
    },
    {
      id: "6",
      title: "Levitating",
      artists: "Dua Lipa feat. DaBaby",
      album: "Future Nostalgia",
      albumColor: ["#FF6978", "#FFE0B2", "#BDD2FF", "#FFC8DD"],
      duration: "03:02",
      playlistName: "Dance your heart out bops",
    },
    {
      id: "7",
      title: "Montero (Call Me By Your Name)",
      artists: "Lil Nas X",
      album: "Montero",
      albumColor: ["#FF1493", "#00FF00", "#0000FF", "#FFFF00"],
      duration: "03:03",
      playlistName: "Unapologetic party anthems",
    },
    {
      id: "8",
      title: "Stay",
      artists: "The Kid LAROI, Justin Bieber",
      album: "F*ck Love",
      albumColor: ["#FF9933", "#FFCC00", "#FFFF99", "#FFE4B5"],
      duration: "03:05",
      playlistName: "Late night feels ballads",
    },
    {
      id: "9",
      title: "drivers license",
      artists: "Olivia Rodrigo",
      album: "SOUR",
      albumColor: ["#FF6978", "#FFE0B2", "#BDD2FF", "#FFC8DD"],
      duration: "03:02",
      playlistName: "Heartbreak and heartache anthems",
    },
    {
      id: "10",
      title: "Therefore I Am",
      artists: "Billie Eilish",
      album: "Happier Than Ever",
      albumColor: ["#00FFFF", "#00008B", "#4B0082", "#FF00FF"],
      duration: "02:23",
      playlistName: "Mood lifting melodies",
    },
  ],
  [
    {
      id: "1",
      title: "abcdefu",
      artists: "GAYLE",
      album: "abcdefu",
      albumColor: ["#FF0000", "#00FF00", "#0000FF", "#FFFF00"],
      duration: "2:34",
      playlistName: "Party Poppin' Dance Floor",
    },
    {
      id: "2",
      title: "drivers license",
      artists: "Olivia Rodrigo",
      album: "SOUR",
      albumColor: ["#FFA500", "#FF00FF", "#00FFFF", "#800080"],
      duration: "2:48",
      playlistName: "Emotional Late Night Cruise",
    },
    {
      id: "3",
      title: "good 4 u",
      artists: "Olivia Rodrigo",
      album: "SOUR",
      albumColor: ["#FFA500", "#FF00FF", "#00FFFF", "#800080"],
      duration: "2:19",
      playlistName: "Breakup Bops For The Soul",
    },
    {
      id: "4",
      title: "STAY",
      artists: "The Kid LAROI, Justin Bieber",
      album: "F*CK LOVE",
      albumColor: ["#FF0000", "#00FF00", "#0000FF", "#FFFF00"],
      duration: "2:56",
      playlistName: "Summer Love Slow Jamz",
    },
    {
      id: "5",
      title: "industry baby",
      artists: "Lil Nas X, Jack Harlow",
      album: "MONTERO",
      albumColor: ["#FFA500", "#FF00FF", "#00FFFF", "#800080"],
      duration: "2:53",
      playlistName: "Bops To Get Hype At The Club",
    },
    {
      id: "6",
      title: "heat waves",
      artists: "glass animals",
      album: "Dreamland",
      albumColor: ["#FF0000", "#00FF00", "#0000FF", "#FFFF00"],
      duration: "3:37",
      playlistName: "Chill Vibes For Late Nights",
    },
    {
      id: "7",
      title: "happier than ever",
      artists: "Billie Eilish",
      album: "Happier Than Ever",
      albumColor: ["#FFA500", "#FF00FF", "#00FFFF", "#800080"],
      duration: "3:01",
      playlistName: "Emo Pop For The Soul",
    },
    {
      id: "8",
      title: "easy on me",
      artists: "Adele",
      album: "30",
      albumColor: ["#FF0000", "#00FF00", "#0000FF", "#FFFF00"],
      duration: "4:09",
      playlistName: "Power Ballads To Belt Out In The Car",
    },
    {
      id: "9",
      title: "anti-hero",
      artists: "Taylor Swift",
      album: "Midnights",
      albumColor: ["#FFA500", "#FF00FF", "#00FFFF", "#800080"],
      duration: "3:06",
      playlistName: "Relatable Pop Hits For Late Nights",
    },
    {
      id: "10",
      title: "As It Was",
      artists: "Harry Styles",
      album: "Harry's House",
      albumColor: ["#FF0000", "#00FF00", "#0000FF", "#FFFF00"],
      duration: "2:51",
      playlistName: "Summer Vibes For The Beach",
    },
  ],
];
