import { colors } from "./color";
import { PlaylistInterface, SongInterface } from "./typesInterface";
import {v4 as uuidv4} from 'uuid';

export const songs: SongInterface[] = [
  {
    id: uuidv4().slice(0, 4),
    title: "I'm a dev 4 you",
    image: `/images/Casette.png`,
    artists: "DJ Toggle",
    album: "Release Beats",
    duration: "2:56",
  },
  {
    id: uuidv4().slice(0, 4),
    title: "Code Me Maybe",
    image: `/images/Code me maybe.png`,
    artists: "Blast Radius",
    album: "Targeted Experience",
    duration: "3:53",
  },
  {
    id: uuidv4().slice(0, 4),
    title: "Crash and Burn",
    image: `/images/Spotlight.png`,
    artists: "The DevOperatos",
    album: "Instant Recovery",
    duration: "2:23",
  },
  {
    id: uuidv4().slice(0, 4),
    title: "MMMbyte",
    image: `/images/Kill switcher cover.png`,
    artists: "Terminal Launch",
    album: "RELEASE",
    duration: "5:13",
  },
  {
    id: uuidv4().slice(0, 4),
    title: "Talk Contexts to Me",
    image: `/images/Used to code me cover.png`,
    artists: "Lost Weekends",
    album: "Reclaim",
    duration: "3:22",
  },
];

export const moreNewSongs: SongInterface[] = [
  {
    id: uuidv4().slice(0, 4),
    title: "I'm a dev 4 you",
    image: `/images/Casette.png`,
    artists: "DJ Toggle",
    album: "Release Beats",
    duration: "2:56",
  },
  {
    id: uuidv4().slice(0, 4),
    title: "Code Me Maybe",
    image: `/images/Code me maybe.png`,
    artists: "Blast Radius",
    album: "Targeted Experience",
    duration: "3:53",
  },
  {
    id: uuidv4().slice(0, 4),
    title: "Crash and Burn",
    image: `/images/Spotlight.png`,
    artists: "The DevOperatos",
    album: "Instant Recovery",
    duration: "2:23",
  },
  {
    id: uuidv4().slice(0, 4),
    title: "MMMbyte",
    image: `/images/Kill switcher cover.png`,
    artists: "Terminal Launch",
    album: "RELEASE",
    duration: "5:13",
  },
  {
    id: uuidv4().slice(0, 4),
    title: "Talk Contexts to Me",
    image: `/images/Used to code me cover.png`,
    artists: "Lost Weekends",
    album: "Reclaim",
    duration: "3:22",
  },
];

export const playlists: PlaylistInterface[] = [
  {
    id: "liked-songs",
    title: "Liked Songs",
    color: colors.emerald,
    cover: "/images/heart.png",
    songs: [...songs,...moreNewSongs]
  },
  {
    id: "shipper-beats",
    title: "Shipper Beats",
    color: colors.pink,
    cover: "/images/Shipper beats cover.png",
    songs: [...songs,...moreNewSongs]
  },
  {
    id: "rollback-mix",
    title: "Rollback Mix",
    color: colors.indigo,
    cover: "/images/Rollback Mix cover.png",
    songs: [...songs,...moreNewSongs]
  },
];

export const moreNewPlaylists: PlaylistInterface[] = [
  {
    id: "launch-party-jams",
    title: "Launch Party Jams",
    color: colors.green,
    cover: "/images/Launch Party Jams cover.png",
    songs: [...songs,...moreNewSongs]
  },
  {
    id:  "cosmic-vibes",
    title: "Cosmic Vibes",
    color: colors.rose,
    cover: "/images/Cosmic vibes cover.png",
    songs: [...songs,...moreNewSongs]
  },
  {
    id: "codebreaker-blues",
    title: "Codebreaker Blues",
    color: colors.blue,
    cover: "/images/Codebreaker blues cover.png",
    songs: [...songs,...moreNewSongs]
  },
];




export const defaultListOfPlaylists = [
  [
    {
      id: "1",
      title: "Good Days",
      artists: "SZA",
      album: "Good Days",
      albumColor: ["#FFB6C1", "#F7727E", "#92C5F2", "#E8AD5C"],
      duration: "3:53",
    },
    {
      id: "2",
      title: "Sunflower",
      artists: "Post Malone ft. Swae Lee",
      album: "Spider-Man: Into the Spider-Verse soundtrack",
      albumColor: ["#EDCF62", "#EDE5C6", "#9B9B9B", "#E5E0A7"],
      duration: "2:38",
    },
    {
      id: "3",
      title: "Leave the Door Open",
      artists: "Bruno Mars, Anderson .Paak, Silk Sonic",
      album: "An Evening With Silk Sonic",
      albumColor: ["#7B3294", "#5D8AA8", "#4B5D6D", "#CBAAC2"],
      duration: "3:11",
    },
    {
      id: "4",
      title: "Physical",
      artists: "Dua Lipa",
      album: "Future Nostalgia",
      albumColor: ["#7B8C98", "#3B47B4", "#283965", "#F4E2D5"],
      duration: "3:13",
    },
    {
      id: "5",
      title: "All Of The Lights",
      artists: "Kanye West",
      album: "My Beautiful Dark Twisted Fantasy",
      albumColor: ["#5D5B6B", "#8A3F77", "#3B3A4F", "#B1B1B1"],
      duration: "5:18",
    },
    {
      id: "6",
      title: "Waste My Time",
      artists: " Eleanor  Gross",
      album: "Urban Stories",
      albumColor: ["#5D7F7B", "#8C5D5B", "#314737", "#CFD2CA"],
      duration: "3:08",
    },
    {
      id: "7",
      title: "Lowkey",
      artists: "The Weeknd",
      album: "After Hours",
      albumColor: ["#651A6F", "#7B5F6F", "#3D2A4F", "#D1BABC"],
      duration: "3:13",
    },
    {
      id: "8",
      title: "Don't Go Yet",
      artists: "Camila Cabello",
      album: "Camila",
      albumColor: ["#5D4054", "#7B6D6B", "#8A5D5E", "#D5BAB0"],
      duration: "2:43",
    },
    {
      id: "9",
      title: "Telepath",
      artists: "Bryan Adams",
      album: "So Happy It Hurts",
      albumColor: ["#553763", "#6B2855", "#7B3A96", "#6B90CA"],
      duration: "3:30",
    },
    {
      id: "10",
      title: "Leave Me Lonely",
      artists: "Marshmello ft. Anne-Marie",
      album: "Speak Your Mind",
      albumColor: ["#FF50E3", "#FF65E3", "#FF9CE4", "#FF29E3"],
      duration: "3:21",
    },
  ],
  [
    {
      id: "1",
      title: "Dynasty",
      artists: "San Holo",
      album: "Stay Vibrant",
      albumColor: ["#EE1C2B", "#03DAC6", "#F2A05A", "#FC5E5C"],
      duration: "3:40",
    },
    {
      id: "2",
      title: "All Of The Girls You Loved Before",
      artists: "Taylor Swift",
      album: "Fearless (Taylor's Version)",
      albumColor: ["#7B16FF", "#7BFF16", "#5E00C3", "#FF2D55"],
      duration: "3:15",
    },
    {
      id: "3",
      title: "Leave the Door Open",
      artists: "Bruno Mars, Anderson .Paak & Silk Sonic",
      album: "An Evening With Silk Sonic",
      albumColor: ["#5C8AA3", "#5C50A3", "#3B3984", "#A85C8A"],
      duration: "3:27",
    },
    {
      id: "4",
      title: "Daydreaming",
      artists: "Harry Styles",
      album: "Fine Line",
      albumColor: ["#7B3E97", "#1A237E", "#D6643F", "#9B80FF"],
      duration: "4:05",
    },
    {
      id: "5",
      title: "All Eyes on Me",
      artists: "BTS",
      album: "Map of the Soul: 7",
      albumColor: ["#2E5894", "#2E-5894", "#25384D", "#7B80BD"],
      duration: "3:11",
    },
    {
      id: "6",
      title: "Peaches",
      artists: "Justin Bieber feat. Daniel Caesar & Giveon",
      album: "Justice",
      albumColor: ["#4B1D99", "#2E8B57", "#6D4F68", "#9B4B6D"],
      duration: "3:09",
    },
    {
      id: "7",
      title: "Stay",
      artists: "The Kid Laroi & Justin Bieber",
      album: "F*CK LOVE (SAVAGE)",
      albumColor: ["#4A136B", "#2C80BA", "#A99734", "#9B3921"],
      duration: "3:32",
    },
    {
      id: "8",
      title: "Mr. Perfectly Fine",
      artists: "Pink Floyd",
      album: "The Later Years",
      albumColor: ["#A8549A", "#505C9A", "#5C2D6D", "#7B686A"],
      duration: "4:09",
    },
    {
      id: "9",
      title: "Deja vu",
      artists: "Olivia Rodrigo",
      album: "SOUR",
      albumColor: ["#7B1F71", "#1A0C5C", "#7B6A1A", "#58A5BD"],
      duration: "3:15",
    },
    {
      id: "10",
      title: "Good 4 U",
      artists: "Olivia Rodrigo",
      album: "SOUR",
      albumColor: ["#7B0A0C", "#2E4E1A", "#A2685A", "#5C80A0"],
      duration: "2:58",
    },
  ],
  [
    {
      id: "1",
      title: "About You",
      artists: "Stray Kids",
      album: "NO EASY",
      albumColor: ["#EEB422", "#E1B62C", "#F57D1A", "#EBCB10"],
      duration: "3:43",
    },
    {
      id: "2",
      title: "Leave the Door Open",
      artists: "Anderson .Paak",
      album: "Venom: Let There Be Carnage (Original Motion Picture Soundtrack)",
      albumColor: ["#4F2A5A", "#8A64B2", "#B24A6B", "#A349A1"],
      duration: "3:26",
    },
    {
      id: "3",
      title: "Peaches",
      artists: "Justin Bieber feat. Daniel Caesar & Giveon",
      album: "Justice",
      albumColor: ["#9B2C1F", "#6F45E6", "#3C3A49", "#1F2529"],
      duration: "3:16",
    },
    {
      id: "4",
      title: "Daylight",
      artists: "Joji",
      album: "Nectar",
      albumColor: ["#55411C", "#7B4226", "#6D693B", "#9B5C70"],
      duration: "2:43",
    },
    {
      id: "5",
      title: "Pepas",
      artists: "Farruko",
      album: "La 167",
      albumColor: ["#C15B31", "#B7664A", "#F5B7A1", "#9E3E1E"],
      duration: "2:59",
    },
    {
      id: "6",
      title: "Deja vu",
      artists: "Olivia Rodrigo",
      album: "SOUR",
      albumColor: ["#3D0C02", "#571F39", "#790F5B", "#1F1B2C"],
      duration: "3:15",
    },
    {
      id: "7",
      title: "Good 4 U",
      artists: "Olivia Rodrigo",
      album: "SOUR",
      albumColor: ["#7B1F1B", "#A3372F", "#BC5651", "#4A0C15"],
      duration: "2:58",
    },
    {
      id: "8",
      title: "Leave Me Lonely",
      artists: "Dua Lipa",
      album: "Future Nostalgia",
      albumColor: ["#9B6E6A", "#B85C56", "#8C5B5B", "#6C3D3D"],
      duration: "3:10",
    },
    {
      id: "9",
      title: "One More Time (feat. Ariana Grande)",
      artists: "Drake",
      album: "Certified Lover Boy",
      albumColor: ["#3D2B1F", "#5B453A", "#7B5B6D", "#2F0A0A"],
      duration: "3:21",
    },
    {
      id: "10",
      title: "C'est la vie",
      artists: "BTS",
      album: "Map of the Soul: 7",
      albumColor: ["#7B5B00", "#AD7200", "#E08E00", "#8B0000"],
      duration: "3:10",
    },
  ],
];
